server:
  port: 8004

spring:
  datasource:
    url: jdbc:mysql://192.168.1.224:3306/qianyue?useSSL=false&serverTimezone=CTT
    username: root
    password: gitlab123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      connection-init-sqls: set names utf8mb4


# https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  reasonable: true

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:mapper/**/*Mapper.xml
